### ISSUE TITLE
Issue with snapper 0.10.7

### ISSUE THREAD

**Issue by ppascher** [enzingerm/snapborg#27]
Yesterday on arch snapper was updated from 0.10.6 to 0.10.7 after which I ran into issues with snapborg:

```
> snapborg list
Listing snapper snapshots:
No permissions.
Traceback (most recent call last):
  File "/usr/bin/snapborg", line 33, in <module>
    sys.exit(load_entry_point('snapborg==0.1.0', 'console_scripts', 'snapborg')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/snapborg/commands/snapborg.py", line 83, in main
    list_snapshots(cfg, configs=configs)
  File "/usr/lib/python3.11/site-packages/snapborg/commands/snapborg.py", line 95, in list_snapshots
    snapper_config = SnapperConfig.get(config["name"])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/snapborg/snapper.py", line 68, in get
    return cls(config_name, run_snapper(["get-config"], config_name))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/snapborg/snapper.py", line 40, in run_snapper
    output = subprocess.check_output(args_new).decode().strip()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['snapper', '-c', 'home', '--jsonout', 'get-config']' returned non-zero exit status 1.
```
Running with sudo works but is not necessary with snapper 0.10.6

Then:
```
> snapborg backup
Backing up snapshots for snapper config 'home'...
No permissions.

Backup results:
FAILED home: Failed to get snapper config home!
Traceback (most recent call last):
  File "/usr/bin/snapborg", line 33, in <module>
    sys.exit(load_entry_point('snapborg==0.1.0', 'console_scripts', 'snapborg')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/snapborg/commands/snapborg.py", line 79, in main
    backup(cfg, snapper_configs=configs, recreate=args.recreate,
  File "/usr/lib/python3.11/site-packages/snapborg/commands/snapborg.py", line 155, in backup
    raise Exception("Snapborg failed!")
Exception: Snapborg failed!
```
After downgrading the snapper package back to 0.10.6 everything works again as expected.

**Comment by enzingerm** [comment]
Closing this as it seems to be fixed in snapper.
